version: '2.1'

services:

  bslayer:
    image: bslayer
    container_name: bslayer
    build:
      context: .
      dockerfile: bs-layer/Dockerfile    
    expose:
      - 8080
    ports:
      - '9442:8080'

  dslayer:
    image: dslayer
    container_name: dslayer
    build:
      context: .
      dockerfile: ds-layer/Dockerfile    
    expose:
      - 8080
    ports:
      - '9443:8080'
